package com.cozary.ore_creeper.util;

import net.neoforged.neoforge.common.ModConfigSpec;

public class ConfigurationHandler {
    public static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
    public static final General GENERAL = new General(BUILDER);
    public static final ModConfigSpec spec = BUILDER.build();

    public static class General {

        public final ModConfigSpec.IntValue coalCreeperWeight;
        public final ModConfigSpec.IntValue coalCreeperminGroupSize;
        public final ModConfigSpec.IntValue coalCreepermaxGroupSize;
        public final ModConfigSpec.IntValue copperCreeperWeight;
        public final ModConfigSpec.IntValue copperCreeperminGroupSize;
        public final ModConfigSpec.IntValue copperCreepermaxGroupSize;
        public final ModConfigSpec.IntValue diamondCreeperWeight;
        public final ModConfigSpec.IntValue diamondCreeperminGroupSize;
        public final ModConfigSpec.IntValue diamondCreepermaxGroupSize;
        public final ModConfigSpec.IntValue emeraldCreeperWeight;
        public final ModConfigSpec.IntValue emeraldCreeperminGroupSize;
        public final ModConfigSpec.IntValue emeraldCreepermaxGroupSize;
        public final ModConfigSpec.IntValue goldCreeperWeight;
        public final ModConfigSpec.IntValue goldCreeperminGroupSize;
        public final ModConfigSpec.IntValue goldCreepermaxGroupSize;
        public final ModConfigSpec.IntValue ironCreeperWeight;
        public final ModConfigSpec.IntValue ironCreeperminGroupSize;
        public final ModConfigSpec.IntValue ironCreepermaxGroupSize;
        public final ModConfigSpec.IntValue lapisLazuliCreeperWeight;
        public final ModConfigSpec.IntValue lapisLazuliCreeperminGroupSize;
        public final ModConfigSpec.IntValue lapisLazuliCreepermaxGroupSize;
        public final ModConfigSpec.IntValue redstoneCreeperWeight;
        public final ModConfigSpec.IntValue redstoneCreeperminGroupSize;
        public final ModConfigSpec.IntValue redstoneCreepermaxGroupSize;
        public final ModConfigSpec.IntValue netherGoldCreeperWeight;
        public final ModConfigSpec.IntValue netherGoldCreeperminGroupSize;
        public final ModConfigSpec.IntValue netherGoldCreepermaxGroupSize;
        public final ModConfigSpec.IntValue netherQuartzCreeperWeight;
        public final ModConfigSpec.IntValue netherQuartzCreeperminGroupSize;
        public final ModConfigSpec.IntValue netherQuartzCreepermaxGroupSize;

        public final ModConfigSpec.DoubleValue oreTntExplosionRadius;
        public final ModConfigSpec.DoubleValue coalCreeperExplosionRadius;
        public final ModConfigSpec.IntValue coalCreeperMaxSpawnYLevel;
        public final ModConfigSpec.DoubleValue copperCreeperExplosionRadius;
        public final ModConfigSpec.IntValue copperCreeperMaxSpawnYLevel;
        public final ModConfigSpec.DoubleValue diamondCreeperExplosionRadius;
        public final ModConfigSpec.IntValue diamondCreeperMaxSpawnYLevel;
        public final ModConfigSpec.DoubleValue emeraldCreeperExplosionRadius;
        public final ModConfigSpec.IntValue emeraldCreeperMaxSpawnYLevel;
        public final ModConfigSpec.DoubleValue goldCreeperExplosionRadius;
        public final ModConfigSpec.IntValue goldCreeperMaxSpawnYLevel;
        public final ModConfigSpec.DoubleValue ironCreeperExplosionRadius;
        public final ModConfigSpec.IntValue ironCreeperMaxSpawnYLevel;
        public final ModConfigSpec.DoubleValue lapisLazuliCreeperExplosionRadius;
        public final ModConfigSpec.IntValue lapisLazuliCreeperMaxSpawnYLevel;
        public final ModConfigSpec.DoubleValue netherGoldCreeperExplosionRadius;
        public final ModConfigSpec.IntValue netherGoldCreeperMaxSpawnYLevel;
        public final ModConfigSpec.DoubleValue netherQuartzCreeperExplosionRadius;
        public final ModConfigSpec.IntValue netherQuartzCreeperMaxSpawnYLevel;
        public final ModConfigSpec.DoubleValue redstoneCreeperExplosionRadius;
        public final ModConfigSpec.IntValue redstoneCreeperMaxSpawnYLevel;

        General(ModConfigSpec.Builder builder) {

            builder.push("General");
            oreTntExplosionRadius = builder.defineInRange("explosion radius", 4.0, 0, 100);
            builder.pop();
            builder.push("Coal Creeper");
            coalCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            coalCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();
            builder.push("Copper Creeper");
            copperCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            copperCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();
            builder.push("Diamond Creeper");
            diamondCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            diamondCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();
            builder.push("Emerald Creeper");
            emeraldCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            emeraldCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();
            builder.push("Gold Creeper");
            goldCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            goldCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();
            builder.push("Iron Creeper");
            ironCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            ironCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();
            builder.push("Lapis Lazuli Creeper");
            lapisLazuliCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            lapisLazuliCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();
            builder.push("Nether Gold Creeper");
            netherGoldCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            netherGoldCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();
            builder.push("Nether Quartz Creeper");
            netherQuartzCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            netherQuartzCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();
            builder.push("Redstone Creeper");
            redstoneCreeperExplosionRadius = builder.defineInRange("explosion radius", 3.75, 0, 100);
            redstoneCreeperMaxSpawnYLevel = builder.defineInRange("max spawn Y level", 320, -64, 320);
            builder.pop();

            builder.push("Spawn Rates - Only fabric");
            builder.comment("Configure Mob spawn weight & min/max group size. Set weight to 0 to disable.");
            builder.pop();
            builder.push("Coal Creeper - Fabric");
            coalCreeperWeight = builder.defineInRange("Weight", 60, 0, 500);
            coalCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            coalCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
            builder.push("Copper Creeper - Fabric");
            copperCreeperWeight = builder.defineInRange("Weight", 60, 0, 500);
            copperCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            copperCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
            builder.push("Diamond Creeper - Fabric");
            diamondCreeperWeight = builder.defineInRange("Weight", 20, 0, 500);
            diamondCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            diamondCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
            builder.push("Emerald Creeper - Fabric");
            emeraldCreeperWeight = builder.defineInRange("Weight", 20, 0, 500);
            emeraldCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            emeraldCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
            builder.push("Gold Creeper - Fabric");
            goldCreeperWeight = builder.defineInRange("Weight", 60, 0, 500);
            goldCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            goldCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
            builder.push("Iron Creeper - Fabric");
            ironCreeperWeight = builder.defineInRange("Weight", 80, 0, 500);
            ironCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            ironCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
            builder.push("Lapis Lazuli Creeper - Fabric");
            lapisLazuliCreeperWeight = builder.defineInRange("Weight", 50, 0, 500);
            lapisLazuliCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            lapisLazuliCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
            builder.push("Redstone Creeper - Fabric");
            redstoneCreeperWeight = builder.defineInRange("Weight", 40, 0, 500);
            redstoneCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            redstoneCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
            builder.push("Nether Gold Creeper - Fabric");
            netherGoldCreeperWeight = builder.defineInRange("Weight", 20, 0, 500);
            netherGoldCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            netherGoldCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
            builder.push("Nether Quartz Creeper - Fabric");
            netherQuartzCreeperWeight = builder.defineInRange("Weight", 20, 0, 500);
            netherQuartzCreeperminGroupSize = builder.defineInRange("Min Group Size", 1, 0, 100);
            netherQuartzCreepermaxGroupSize = builder.defineInRange("Max Group Size", 2, 0, 100);
            builder.pop();
        }
    }
}