# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version_forge=2.0.3
version_fabric=2.0.3
version_neoforge=2.0.3
group=com.cozary.ore_creeper
java_version=25

# Common
minecraft_version=26.2
mod_name=Ore Creeper
mod_author=Cozary
mod_id=ore_creeper
license=All Rights Reserved
credits=Thanks for download this mod uwu
description=Add a variety of Creepers based on the Ores in the game. With their explosion they generate resources!
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric https://fabricmc.net/develop/
fabric_version=0.158.0+26.2
fabric_loader_version=0.19.3

# Forge https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=65.1.0
forge_loader_version_range=[65,)

# NeoForge https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.66
neoforge_loader_version_range=[4,)

# Publishing
mod_publish_version=2.2.0
dry_run=false
curseforge_project_id=560542
modrinth_project_id=CGmwbV8J

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
