# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version_forge=1.2.3
version_fabric=1.0.3
version_neoforge=1.0.3
group=com.cozary.ore_creeper
java_version=21
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.4
parchment_version=2024.12.07

# Common
minecraft_version=1.21.4
mod_name=Ore Creeper
mod_author=Cozary
mod_id=ore_creeper
license=All Rights Reserved
credits=Thanks for download this mod uwu
description=Add a variety of Creepers based on the Ores in the game. With their explosion they generate resources!
minecraft_version_range=[1.21.4, 1.22)

# Fabric
fabric_version=0.112.1+1.21.4
fabric_loader_version=0.16.9

# Forge
forge_version=54.0.6
forge_loader_version_range=[54,)

# NeoForge
neoforge_version=21.4.30-beta
neoforge_loader_version_range=[4,)

# Mod Support
# https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files/all?page=1&pageSize=20
forge_config_api=21.4.1

# Publishing
mod_publish_version=0.8.4
dry_run=false
curseforge_project_id=560542
modrinth_project_id=CGmwbV8J
version=1.0.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
